apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
  type: LoadBalancer
## By default type is ClusterIP, which is only accessible within the cluster
## LoadBalancer type is accessible from outside the cluster
