apiVersion: v1
kind: Pod
metadata:
  name: my-pod

spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
    - name: redis
      image: redis:6.2.5
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
# kubeclt apply -f first-pod.yaml
# kubeclt get pods
# kubeclt get pods -w
