apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30500
      ## port: 5672: The port on which the Service is exposed.
      ## targetPort: 5672: The port on the Pod that the Service should forward traffic to.
      ## nodePort: 30500: The port on each Node to expose the Service.
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 30501
