apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
## Using ReplicaSet to create 3 pods, with labels defined in metadata.labels
## Selector will pick up matchLabels to create 3 replica pods

# kubectl apply -f replica-set.yaml
# kubectl get replicaset
# kubectl delete replicaset my-replicaset-xxxxx

# If a pod is deleted, ReplicaSet will create a new pod to maintain the number of pods
